unsafe extern "C" fn zelda_specialn_pre(fighter: &mut L2CFighterCommon) -> L2CValue {
    fighter.sub_status_pre_SpecialNCommon().get_bool();
    aLStack120 = FIGHTER_LITTLEMAC_STATUS_KIND_SPECIAL_N_MAX_DASH_TURN._4_4_;
    aLStack136 = FIGHTER_KINETIC_TYPE_UNIQ;
    aLStack152 = GROUND_CORRECT_KIND_KEEP;
    aLStack168 = GROUND_CLIFF_CHECK_KIND_NONE;
    aLStack184 = true;
    aLStack200 = FIGHTER_STATUS_WORK_KEEP_FLAG_NONE_FLAG;
    aLStack216 = FIGHTER_STATUS_WORK_KEEP_FLAG_NONE_INT;
    aLStack232 = FIGHTER_STATUS_WORK_KEEP_FLAG_NONE_FLOAT;
    aLStack248 = 0;
    SVar5 = aLStack120;
    iVar6 = aLStack136;
    uVar7 = aLStack152;
    GVar8 = aLStack168;
    bVar1 = aLStack184;
    iVar9 = aLStack200;
    iVar10 = aLStack216;
    iVar11 = aLStack232;
    aLStack248;
    StatusModule::init_settings(fighter.module_accessor, SVar5, iVar6, uVar7, GVar8, bVar1, iVar9, iVar10, iVar11, in_stack_fffffffffffffef4);
    lib::L2CValue::_L2CValue(aLStack248);
    lib::L2CValue::_L2CValue(aLStack232);
    lib::L2CValue::_L2CValue(aLStack216);
    lib::L2CValue::_L2CValue(aLStack200);
    lib::L2CValue::_L2CValue(aLStack184);
    lib::L2CValue::_L2CValue(aLStack168);
    lib::L2CValue::_L2CValue(aLStack152);
    lib::L2CValue::_L2CValue(aLStack136);
    lib::L2CValue::_L2CValue(aLStack120);
    aLStack120 = false;
    aLStack136 = FIGHTER_TREADED_KIND_NO_REAC;
    aLStack152 = false;
    aLStack168 = false;
    aLStack184 = false;
    aLStack200 = FIGHTER_LOG_MASK_FLAG_ATTACK_KIND_SPECIAL_N | FIGHTER_LOG_MASK_FLAG_ACTION_CATEGORY_ATTACK | FIGHTER_LOG_MASK_FLAG_ACTION_TRIGGER_ON;
    aLStack216 = FIGHTER_STATUS_ATTR_START_TURN;
    aLStack232 = FIGHTER_POWER_UP_ATTACK_BIT_SPECIAL_N;
    aLStack248 = 0;
    bVar1 = aLStack120;
    iVar6 = aLStack136;
    bVar2 = aLStack152;
    bVar3 = aLStack168;
    bVar4 = aLStack184;
    uVar13 = aLStack200;
    uVar7 = aLStack216;
    uVar12 = aLStack232;
    aLStack248;
    FighterStatusModuleImpl::set_fighter_status_data(fighter.module_accessor, (bVar1 & 1), iVar6, (bVar2 & 1), (bVar3 & 1), bVar4, uVar13, uVar7, uVar12, in_stack_fffffffffffffef4);
    lib::L2CValue::_L2CValue(aLStack248);
    lib::L2CValue::_L2CValue(aLStack232);
    lib::L2CValue::_L2CValue(aLStack216);
    lib::L2CValue::_L2CValue(aLStack200);
    lib::L2CValue::_L2CValue(aLStack184);
    lib::L2CValue::_L2CValue(aLStack168);
    lib::L2CValue::_L2CValue(aLStack152);
    lib::L2CValue::_L2CValue(aLStack136);
    lib::L2CValue::_L2CValue(aLStack120);
    return_value = 0;
    return return_value.into();
}
